-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- PROGRAM		"Quartus II 32-bit"
-- VERSION		"Version 13.1.0 Build 162 10/23/2013 SJ Web Edition"
-- CREATED		"Thu Feb 27 21:32:06 2025"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY Traffic IS 
	PORT
	(
		clock :  IN  STD_LOGIC;
		reset :  IN  STD_LOGIC;
		EWG :  OUT  STD_LOGIC;
		EWY :  OUT  STD_LOGIC;
		EWR :  OUT  STD_LOGIC;
		NSY :  OUT  STD_LOGIC;
		NSG :  OUT  STD_LOGIC;
		NSR :  OUT  STD_LOGIC
	);
END Traffic;

ARCHITECTURE bdf_type OF Traffic IS 

COMPONENT lpm_counter0
	PORT(clock : IN STD_LOGIC;
		 aclr : IN STD_LOGIC;
		 q : OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
	);
END COMPONENT;

SIGNAL	A :  STD_LOGIC;
SIGNAL	B :  STD_LOGIC;
SIGNAL	C :  STD_LOGIC;
SIGNAL	D :  STD_LOGIC;
SIGNAL	q :  STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_0 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_1 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_2 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_3 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_4 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_5 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_6 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_7 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_8 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_9 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_10 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_11 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_12 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_13 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_14 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_15 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_16 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_17 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_18 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_19 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_20 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_21 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_22 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_23 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_24 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_25 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_26 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_27 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_28 :  STD_LOGIC;


BEGIN 



NSY <= SYNTHESIZED_WIRE_0 AND B AND C;


SYNTHESIZED_WIRE_0 <= NOT(A);



SYNTHESIZED_WIRE_26 <= SYNTHESIZED_WIRE_1 AND B AND SYNTHESIZED_WIRE_2;


SYNTHESIZED_WIRE_25 <= SYNTHESIZED_WIRE_3 AND SYNTHESIZED_WIRE_4 AND SYNTHESIZED_WIRE_5 AND D;


SYNTHESIZED_WIRE_1 <= NOT(A);



SYNTHESIZED_WIRE_2 <= NOT(C);



SYNTHESIZED_WIRE_27 <= NOT(A);



SYNTHESIZED_WIRE_28 <= NOT(B);



SYNTHESIZED_WIRE_3 <= NOT(A);



SYNTHESIZED_WIRE_4 <= NOT(B);



SYNTHESIZED_WIRE_5 <= NOT(C);



EWY <= A AND B AND C;


NSR <= SYNTHESIZED_WIRE_6 OR A;


EWR <= SYNTHESIZED_WIRE_7 OR SYNTHESIZED_WIRE_8;


SYNTHESIZED_WIRE_8 <= NOT(A);



SYNTHESIZED_WIRE_7 <= A AND SYNTHESIZED_WIRE_9 AND SYNTHESIZED_WIRE_10 AND SYNTHESIZED_WIRE_11;


SYNTHESIZED_WIRE_9 <= NOT(B);



SYNTHESIZED_WIRE_10 <= NOT(C);



SYNTHESIZED_WIRE_11 <= NOT(D);



EWG <= SYNTHESIZED_WIRE_12 OR SYNTHESIZED_WIRE_13 OR SYNTHESIZED_WIRE_14;


SYNTHESIZED_WIRE_14 <= A AND B AND SYNTHESIZED_WIRE_15;


SYNTHESIZED_WIRE_15 <= NOT(C);



SYNTHESIZED_WIRE_12 <= A AND SYNTHESIZED_WIRE_16 AND C;


SYNTHESIZED_WIRE_6 <= SYNTHESIZED_WIRE_17 AND SYNTHESIZED_WIRE_18 AND SYNTHESIZED_WIRE_19 AND SYNTHESIZED_WIRE_20;


SYNTHESIZED_WIRE_16 <= NOT(B);



SYNTHESIZED_WIRE_13 <= A AND SYNTHESIZED_WIRE_21 AND SYNTHESIZED_WIRE_22 AND D;


SYNTHESIZED_WIRE_21 <= NOT(B);



b2v_inst33 : lpm_counter0
PORT MAP(clock => clock,
		 aclr => SYNTHESIZED_WIRE_23,
		 q => q);


SYNTHESIZED_WIRE_22 <= NOT(C);



SYNTHESIZED_WIRE_23 <= NOT(reset);


C <= q(1);


B <= q(2);


A <= q(3);


D <= q(0);



SYNTHESIZED_WIRE_19 <= NOT(C);



SYNTHESIZED_WIRE_20 <= NOT(D);



SYNTHESIZED_WIRE_18 <= NOT(B);



SYNTHESIZED_WIRE_17 <= NOT(A);



NSG <= SYNTHESIZED_WIRE_24 OR SYNTHESIZED_WIRE_25 OR SYNTHESIZED_WIRE_26;


SYNTHESIZED_WIRE_24 <= SYNTHESIZED_WIRE_27 AND SYNTHESIZED_WIRE_28 AND C;


END bdf_type;