-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- PROGRAM		"Quartus II 32-bit"
-- VERSION		"Version 13.1.0 Build 162 10/23/2013 SJ Web Edition"
-- CREATED		"Wed Feb 26 19:52:58 2025"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY primeExtension IS 
	PORT
	(
		A :  IN  STD_LOGIC;
		B :  IN  STD_LOGIC;
		C :  IN  STD_LOGIC;
		D :  IN  STD_LOGIC;
		E :  IN  STD_LOGIC;
		F :  IN  STD_LOGIC;
		O :  OUT  STD_LOGIC
	);
END primeExtension;

ARCHITECTURE bdf_type OF primeExtension IS 

SIGNAL	SYNTHESIZED_WIRE_56 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_57 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_2 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_3 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_58 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_5 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_6 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_8 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_9 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_10 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_11 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_59 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_14 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_15 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_16 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_17 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_18 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_22 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_23 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_28 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_29 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_33 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_34 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_60 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_38 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_39 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_41 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_42 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_43 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_44 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_45 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_46 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_47 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_48 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_50 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_51 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_53 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_54 :  STD_LOGIC;


BEGIN 



SYNTHESIZED_WIRE_41 <= SYNTHESIZED_WIRE_56 AND SYNTHESIZED_WIRE_57 AND E AND F;


SYNTHESIZED_WIRE_14 <= SYNTHESIZED_WIRE_2 AND SYNTHESIZED_WIRE_3;


SYNTHESIZED_WIRE_5 <= A AND C AND SYNTHESIZED_WIRE_58;


SYNTHESIZED_WIRE_6 <= E AND F;


SYNTHESIZED_WIRE_15 <= SYNTHESIZED_WIRE_5 AND SYNTHESIZED_WIRE_6;


SYNTHESIZED_WIRE_10 <= SYNTHESIZED_WIRE_56 AND B AND D;


SYNTHESIZED_WIRE_11 <= E AND F;


O <= SYNTHESIZED_WIRE_8 OR SYNTHESIZED_WIRE_9;


SYNTHESIZED_WIRE_45 <= SYNTHESIZED_WIRE_10 AND SYNTHESIZED_WIRE_11;


SYNTHESIZED_WIRE_17 <= A AND SYNTHESIZED_WIRE_59 AND C;


SYNTHESIZED_WIRE_18 <= SYNTHESIZED_WIRE_58 AND F;


SYNTHESIZED_WIRE_8 <= SYNTHESIZED_WIRE_14 OR SYNTHESIZED_WIRE_15 OR SYNTHESIZED_WIRE_16;


SYNTHESIZED_WIRE_16 <= SYNTHESIZED_WIRE_17 AND SYNTHESIZED_WIRE_18;


SYNTHESIZED_WIRE_22 <= SYNTHESIZED_WIRE_56 AND B AND SYNTHESIZED_WIRE_57;


SYNTHESIZED_WIRE_23 <= SYNTHESIZED_WIRE_58 AND F;


SYNTHESIZED_WIRE_46 <= SYNTHESIZED_WIRE_22 AND SYNTHESIZED_WIRE_23;


SYNTHESIZED_WIRE_28 <= SYNTHESIZED_WIRE_56 AND SYNTHESIZED_WIRE_59 AND SYNTHESIZED_WIRE_57;


SYNTHESIZED_WIRE_29 <= SYNTHESIZED_WIRE_58 AND E;


SYNTHESIZED_WIRE_43 <= SYNTHESIZED_WIRE_28 AND SYNTHESIZED_WIRE_29;


SYNTHESIZED_WIRE_33 <= SYNTHESIZED_WIRE_56 AND SYNTHESIZED_WIRE_59 AND SYNTHESIZED_WIRE_58;


SYNTHESIZED_WIRE_34 <= E AND F;


SYNTHESIZED_WIRE_42 <= SYNTHESIZED_WIRE_33 AND SYNTHESIZED_WIRE_34;


SYNTHESIZED_WIRE_38 <= SYNTHESIZED_WIRE_56 AND SYNTHESIZED_WIRE_59 AND D;


SYNTHESIZED_WIRE_39 <= SYNTHESIZED_WIRE_60 AND F;


SYNTHESIZED_WIRE_44 <= SYNTHESIZED_WIRE_38 AND SYNTHESIZED_WIRE_39;


SYNTHESIZED_WIRE_50 <= A AND SYNTHESIZED_WIRE_57 AND D;


SYNTHESIZED_WIRE_56 <= NOT(A);



SYNTHESIZED_WIRE_59 <= NOT(B);



SYNTHESIZED_WIRE_57 <= NOT(C);



SYNTHESIZED_WIRE_9 <= SYNTHESIZED_WIRE_41 OR SYNTHESIZED_WIRE_42 OR SYNTHESIZED_WIRE_43 OR SYNTHESIZED_WIRE_44 OR SYNTHESIZED_WIRE_45 OR SYNTHESIZED_WIRE_46 OR SYNTHESIZED_WIRE_47 OR SYNTHESIZED_WIRE_48;


SYNTHESIZED_WIRE_58 <= NOT(D);



SYNTHESIZED_WIRE_60 <= NOT(E);




SYNTHESIZED_WIRE_51 <= SYNTHESIZED_WIRE_60 AND F;


SYNTHESIZED_WIRE_48 <= SYNTHESIZED_WIRE_50 AND SYNTHESIZED_WIRE_51;


SYNTHESIZED_WIRE_53 <= B AND C AND D;


SYNTHESIZED_WIRE_54 <= SYNTHESIZED_WIRE_60 AND F;


SYNTHESIZED_WIRE_47 <= SYNTHESIZED_WIRE_53 AND SYNTHESIZED_WIRE_54;


SYNTHESIZED_WIRE_2 <= A AND SYNTHESIZED_WIRE_59 AND C;


SYNTHESIZED_WIRE_3 <= E AND F;


END bdf_type;